### ISSUE TITLE
"векторные" вместо "растровые"?

### ISSUE THREAD

**Issue by kechsin** [agricolamz/daR4hs#1]
Возможно я не права, но вот такая цитата из начала 7 урока (7.1):

> Картографические данные могут попадать в разные типы: точки (столицы всех стран), линии (улицы в каком-нибудь городе), полигоны (границы стран и меньших регионов) обычно имеют некоторую геопривязку (для простоты давайте считать таким все, что имеет широту и долготу), так что могут быть представлены **векторно**, однако существует достаточно много информации, которую невозможно представить никак по-другому, кроме как **векторно**: спутниковые снимки, существующие физические/политические/климатические/исторические и т. п. карты

Кажется, что не должно быть оба раза векторно, и по смыслу второе это скорее растрово.

**Comment by agricolamz** [comment]
Спасибо большое, поправлю!
